added fab
regmarcos/kotlin-mvvm-clean-sample pull request #6
Opened 2020-02-17 16:07 UTC by regmarcos

Hi guys! I just added the floating actions buttons to get all the characters from remote and repository and also a button to clear out the recycler.

![pr6](https://user-images.githubusercontent.com/56684939/74669527-0f287a80-5186-11ea-81d0-1a4fc0dab27c.gif)

2020-02-17 16:50 UTC, BQuinteros commented on data/src/main/java/com/globant/data/database/CharacterDatabase.kt
> +        return Result.Failure(Exception("Not found"))
pls try to use EMPTY_STRING utils

2020-02-17 17:16 UTC, SartiMau approved these changes

2020-02-18 14:35 UTC, lucianoeli approved these changes

2020-02-18 14:45 UTC, nicolbidone approved these changes

2020-02-18 17:24 UTC, SartiMau submitted a review, later dismissed

2020-02-18 17:33 UTC, SartiMau reviewed
The storage FAB, I see that it only loads the info from the DB, possibly when the service responds, you save it in Realm... but it shouldn't have another icon in the UI and besides have a different name?

2020-02-19 13:22 UTC, regmarcos commented
i have changed the icon as you request Mauro
![Anotación 2020-02-19 101458](https://user-images.githubusercontent.com/56684939/74838088-b251cf00-5301-11ea-9c70-79863a99dbc1.png)

2020-02-19 14:48 UTC, SartiMau requested changes

2020-02-19 14:48 UTC, SartiMau commented on app/src/main/java/com/globant/activities/CharactersActivity.kt
> +import kotlinx.android.synthetic.main.activity_main_recyclerview.*
don't use wildcard imports pls

2020-02-19 14:54 UTC, regmarcos commented on app/src/main/java/com/globant/activities/CharactersActivity.kt
> +import kotlinx.android.synthetic.main.activity_main_recyclerview.*
done

2020-02-19 15:05 UTC, SartiMau approved these changes

2020-02-20 12:39 UTC, merged