Marcos.reginato/testing fabs
regmarcos/kotlin-mvvm-clean-sample pull request #7
Opened 2020-02-20 12:47 UTC by regmarcos

Hi guys! Now the button's methods are tested too. As you can see the class has the 100% coverage.

Here is the evidence
![coverage pr7](https://user-images.githubusercontent.com/56684939/74934934-0d4cfa00-53c6-11ea-81af-f2d49240ed03.png)
![tests pr7](https://user-images.githubusercontent.com/56684939/74934939-0e7e2700-53c6-11ea-8d3c-7facc41a329a.png)

2020-02-20 13:19 UTC, nicolbidone requested changes

2020-02-20 13:19 UTC, nicolbidone commented on app/src/test/java/com/globant/myapplication/CharacterViewModelTest.kt
> +        //declareMock<GetRepositoryUseCase>()
pls delete commented lines

2020-02-20 13:21 UTC, regmarcos commented on app/src/test/java/com/globant/myapplication/CharacterViewModelTest.kt
> +        //declareMock<GetRepositoryUseCase>()
done

2020-02-20 13:27 UTC, SartiMau submitted a review, later dismissed

2020-02-20 13:27 UTC, nicolbidone approved these changes

2020-02-21 13:44 UTC, BQuinteros commented on app/src/test/java/com/globant/viewmodels/RecyclerCharactersViewModelTest.kt
> +
Remove extra space pls

2020-02-21 13:53 UTC, regmarcos commented on app/src/test/java/com/globant/viewmodels/RecyclerCharactersViewModelTest.kt
> +
done

2020-02-21 13:54 UTC, BQuinteros approved these changes

2020-02-21 18:22 UTC, nicolbidone approved these changes

2020-02-25 20:56 UTC, SartiMau approved these changes

2020-02-25 20:56 UTC, merged